enum EnumSnackbarNotificationKeys {
	KICKED_BY_ADMIN = 'KICKED_BY_ADMIN',
	BULK_SELECTED_CHANNELS_UPDATE = 'BULK_SELECTED_CHANNELS_UPDATE',
	BULK_MESSAGE_SENT = 'BULK_MESSAGE_SENT',
	CAMERA_PERMISSION = 'CAMERA_PERMISSION_NOTIFICATION_KEY',
	SOFT_CHAT_IS_ON = 'SOFT_CHAT_IS_ON',
	QUERY_REQUEST = 'QUERY_REQUEST',
	RECORD_AUDIO_IF_ONLINE = 'RECORD_AUDIO_IF_ONLINE',
	GROUP_CHANGED_NOTIFICATION_KEY = 'GROUP_CHANGED_NOTIFICATION_KEY',
	CANCELLED_TICKETSHOW = 'CANCELLED_TICKETSHOW',
}

export default EnumSnackbarNotificationKeys;
