enum EnumStore {
	GEOCODING = 'GEOCODING',
	USER = 'USER',
	INFORMATION = 'INFORMATION',
	CATEGORY_OBJECT = 'CATEGORY_OBJECT',
	SUBCATEGORY_OBJECT = 'SUBCATEGORY_OBJECT',
	NOTIFICATIONS = 'NOTIFICATIONS',
	CLIENT = 'CLIENT',
	PLACES = 'PLACES',
	EVENTS = 'EVENTS',
	ROUTES = 'ROUTES',
	SPECIAL_PLACES = 'SPECIAL_PLACES',
}

export default EnumStore;
